### ISSUE TITLE
improve clarity through clearer naming

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ingest-validation-tools#327]
`validate_assay` instead of `validate_submission`?
`validate_samples` instead of `validate_sample`

Generally, where we used "dataset" we might want to consider using assay.

@cebriggs7135 do you have any thoughts on this?

**Comment by mccalluc** [comment]
> `validate_assay` instead of `validate_submission`?

No: It actually does validate whole submission directories, including multiple assay types. It hasn't been used by the PSC up till now because they just had to deal with the data in the form it was delivered, but Bill is aware of it, and would like to use it.

> `validate_samples` instead of `validate_sample`?

Sure.

> Generally, where we used "dataset" we might want to consider using assay.

"Dataset" is used in the portal. We have "assay types" but "assay" by itself isn't really a term we use. I would prefer not to change.
