### ISSUE TITLE
Ambiguous error in 'donor_id' in tsv validation

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#713]
Hi all, thanks for your responsiveness on my recent issues.. I am getting the following error around donor ids. 12/16 in the metadata pass without problem. There are some repeat `donor_id`s.

```
Metadata TSV Errors: U:\TUDelftShare\BIOMIC-DR2-2D-prepared\clean-af-metadata.tsv (as af): Internal: On row 10, column "donor_id", value "VAN0030" fails because incremented sequence of 3 items; limit is 3.

Metadata TSV Errors: U:\TUDelftShare\BIOMIC-DR2-2D-prepared\clean-af-metadata.tsv (as af): Internal: On row 11, column "donor_id", value "VAN0031" fails because incremented sequence of 4 items; limit is 3.

Metadata TSV Errors: U:\TUDelftShare\BIOMIC-DR2-2D-prepared\clean-af-metadata.tsv (as af): Internal: On row 16, column "donor_id", value "VAN0034" fails because incremented sequence of 3 items; limit is 3.

Metadata TSV Errors: U:\TUDelftShare\BIOMIC-DR2-2D-prepared\clean-af-metadata.tsv (as af): Internal: On row 17, column "donor_id", value "VAN0035" fails because incremented sequence of 4 items; limit is 3.
```

all donor_ids:
```
VAN0006
VAN0010
VAN0012
VAN0012
VAN0013
VAN0016
VAN0028
VAN0029
VAN0030
VAN0031
VAN0031
VAN0032
VAN0032
VAN0033
VAN0034
VAN0035
```

**Comment by NHPatterson** [comment]
Here is the .tsv in question (saved as .txt because GH won't let me drop a .tsv file in the comment): 
[af-metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6443610/af-metadata.txt)

**Comment by mccalluc** [comment]
@NHPatterson -- This error arises when values in successive rows are increment by one: This can happen when folks mean to fill a constant value down a column, but instead Excel "helpfully" auto-increments it... but as you've seen, there can also be false positives.
- If you've got an idea about how to better explain that in the error message, happy to change.
- [When it was originally implemented](https://github.com/hubmapconsortium/ingest-validation-tools/pull/568#issuecomment-786052701), the call was that when users did hit a false positive, they should reorder the rows to avoid setting off the warning.
- ... but we have loosened it on Antibodies, because the IDs there are very often sequential integers, and perhaps Donor IDs are another field to be excluded. If you think that's the best course, I'd like to get buy-in from @cebriggs7135 .

**Comment by cebriggs7135** [comment]
@mccalluc You have my buy-in to loosen the increment constraint.
