### ISSUE TITLE
root directories are seen as unreferenced despite data present in their sub-directories

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#715]
This is nearing the last issue I will file, promise!

For our data release, we group data files from the same section like so, with the metadata `.tsv` files in the root directory.
#### schema in root directory
```yaml
# first sample
sample-id-1/
	sample-id-1-assay1-subfolder/
		expected-assay1-folders/files
	sample-id-1-assay2-subfolder/
		expected-assay2-folders/files	

# second sample
sample-id-2/
	sample-id-2-assay1-subfolder/
		expected-assay1-folders/files
	sample-id-2-assay2-subfolder/
		expected-assay2-folders/files	

# multi-line assay metadata for all samples in root directory
assay1-metadata.tsv
assay2-metadata.tsv
```

#### example
```yaml
VAN0006-LK-4-35/
	VAN0006-LK-4-35-AF/
		processedMicroscopy/
		rawMicroscopy/
	VAN0006-LK-4-35-PAS/
		processedMicroscopy/
		rawMicroscopy/
	VAN0006-LK-4-35-IMS/
		VAN0006-LK-4-35-IMS_lipids_neg_mode/
			csv/
			extras/
			imzML/
			metadata/
			ometiffs/
				separate/
		VAN0006-LK-4-35-IMS_lipids_pos_mode/
			csv/
			extras/
			imzML/
			metadata/
			ometiffs/
				separate/

# and on and on for each sample_id

af-metadata.tsv
pas-metadata.tsv
ims-metadata.tsv

```

The metadata.tsv for each assay points to the correct directory and finds the correct files. However, we are getting a notification (warning?) like this for all the `sample_id` directory:
```
There are no references from any TSV to VAN0006-LK-4-35.
```

This notification appears despite the data within subdirectories of the root directory being checked and validated. Might need to walk back up the directory tree here.

**Comment by mccalluc** [comment]
We want to make sure that all the data that's uploaded is referenced by the metadata.tsv: Otherwise we can be in a confusing state where the TMC thinks the data has been submitted, but with the metadata it doesn't get ingested. This check is easy if we say that datasets are at at the top level, right beside the metadata.tsv... If we need to start walking down the directory tree things get harder... If also makes it possible to accidentally create nested datasets, if a path in the metadata.tsv is truncated. The code gets more complicated, and the error messages you'd need to read get more complicated, too.

I'd prefer to close with without making changes... but if you really, really need this, please comment.

**Comment by NHPatterson** [comment]
Gotcha, I understand. Let me try another way to organize the .tsv files and see if I encounter new errors.

**Comment by NHPatterson** [comment]
Ok, I can reorganize our data, but I still think the previous organization is neater. I now have 64 directories, one for each dataset to be uploaded. Previously 64 were organized by their "collection" (i.e., all the spatially related data was in one folder from one donor and one tissue section). I don't think this needs to change right away but I would consider these things carefully for a future release. More flexibility will allow less computer-savvy users to more easily submit their data.
