### ISSUE TITLE
Subtyping of codex-submissions?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#78]
For codex submissions, I’m currently distinguishing akoya and stanford… it could be merged, but that would make it a lot harder to understand the error messages.

**Comment by cebriggs7135** [comment]
I'll confirm with Alex, Elizabeth & Jesus but I think those Stanford submissions will be standardized to Akoya output format everyone else doing CODEX will have. Stanford (the CODEX inventor's team) just does it a little differently because they have superior custom-built software for processing. You should rely on the CODEX document.

**Comment by mccalluc** [comment]
Both structures are in the document. Will wait to hear more.

**Comment by cebriggs7135** [comment]
Let's discuss this on Monday so I can understand what your talking about.

**Comment by cebriggs7135** [comment]
By structures, do you mean the file & folder structure? I don't think that's relevant to the ingest form which will be the same for both sources.

**Comment by mccalluc** [comment]
But we're also validating the files, not just the TSV.

**Comment by mccalluc** [comment]
So to close the loop, the file structures are different, and we'll indicate which it is in the filename: either codex-stanford-metadata.tsv or codex-akoya-metadata.tsv.
