### ISSUE TITLE
Delete cache if load fails?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#896]
@jswelling reports:
> we're having a problem being reported by frictionless inside table_validator at line 25: ... .  The error frictionless is reporting is 'db type is dbm.gnu, but the module is not available' , for which stackoverflow suggests that there is some sort of caching issue.  If you have any idea about how to deal with it I'd love to hear it.

Maybe just delete the cache file if it can't be read? ... but it would be good to understand what's causing it ...

**Comment by mccalluc** [comment]
@jswelling :
> We've found a work-around.  I think the problem is ultimately caused by the fact that the version of python3.6 on the node running the Airflow scheduler includes the module dbm.gnu but the one on Bridges2 (loaded from anaconda) does not.  Clearing the right cache might help but it's not certain that it would solve the problem.

I'm a little confused. Are both runs trying to read the same cache file on disk? If that's what you need, we could use a more portable format for the cache file. Let me know if I'm understanding the problem correctly.

**Comment by mccalluc** [comment]
Moving to a less fragile cache format in #897: This issue was a misdiagnosis.

**Comment by jswelling** [comment]
I believe the mechanism is the the following, but this has not been verified:
* The Airflow scheduler, running on HIVE, produces a pickle data structure describing a validation task to be done.  This includes classes from Frictionless, which are built using the default dbm option dbm.gnu . 
* That pickle gets sent to a Celery worker for execution.  The worker is on Bridges2, and is running a python supplied by anaconda rather than by the old CentOS 'scl' mechanism.
* The anaconda dbm module does not include dbm.gnu, so un-pickling the work task fails.
One solution that might work would be to ask Frictionless to use one of the other dbm options, choosing one which is present in both versions of python.
